front+back/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=320)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $active;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $admin_level;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_connection;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $register_ip;

    /**
     * @ORM\Column(type="datetime")
     */
    private $register_date;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $activation_token;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getActive(): ?string
    {
        return $this->active;
    }

    public function setActive(?string $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getAdminLevel(): ?string
    {
        return $this->admin_level;
    }

    public function setAdminLevel(?string $admin_level): self
    {
        $this->admin_level = $admin_level;

        return $this;
    }

    public function getLastConnection(): ?\DateTimeInterface
    {
        return $this->last_connection;
    }

    public function setLastConnection(\DateTimeInterface $last_connection): self
    {
        $this->last_connection = $last_connection;

        return $this;
    }

    public function getRegisterIp(): ?string
    {
        return $this->register_ip;
    }

    public function setRegisterIp(string $register_ip): self
    {
        $this->register_ip = $register_ip;

        return $this;
    }

    public function getRegisterDate(): ?\DateTimeInterface
    {
        return $this->register_date;
    }

    public function setRegisterDate(\DateTimeInterface $register_date): self
    {
        $this->register_date = $register_date;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    public function setActivationToken(string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }
}

front+back/templates/base.html.twig
{% set route = app.request.attributes.get('_route') %} {% set session = app.session %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">

    <!-- Recaptcha -->
    <script src='https://www.google.com/recaptcha/api.js'></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    

    {# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> #} 

    {# <link rel="stylesheet" href="css/style.css"> #}
    {# <title>{% block title %}{% endblock %}</title> #}
	<link rel="icon" href="{{ asset('images/logo3dark.ico') }}" />
	<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}"> 
	<link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}">
	<link rel="stylesheet" href="{{ asset('css/style.css') }}">
	
	 {% block stylesheets %} {% endblock %}

     <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<header>

<!--
    HEADER
-->
<header id="main_header">
        <div class="main_header_content row">
            <div class="col-4">
                <a id="btn_menu"><i class="fas fa-bars"></i><i class="hide fas fa-times"></i></a>
            </div>
            <div class="col-8 col-md-4 logo_container">
                <a class="logo" href="{{ path('home') }}">L'Yonne en 3D</a>
            </div>
                {# Si pas de session de connecté on affiche #}

                {% if app.session.get('account') is null %}

            <div class="col-md-4 login_container text-right">
                    <a type="button" class="btn btn-primary"  href="{{ path('register') }}">S'inscrire</a>
                    <a type="button" class="btn btn-secondary"  href="{{ path('api_login') }}">Connexion</a>
                </div>

                {# sinon on affiche: #}

                {% else %}

                <div class="col-md-4 login_container text-right">
                        <a type="button" class="btn btn-primary"  href="{{ path('profile') }}">Mon compte</a>
                        <a type="button" class="btn btn-secondary"  href="{{ path('api_logout') }}">Deconnexion</a>
                        <a type="button" class="btn btn-secondary"  href="{{ path('api_upload') }}">upload</a>
                    </div>
                {% endif %}
            </div>
        </header>

        <!--MODAL LOGIN-->
        <div class="modal fade" id="login_modal" tabindex="-1" role="dialog" aria-labelledby="login_modal_label" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="login_modal_label">Connexion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <form class="sign_form a4">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                <input type="email" class="form-control" id="inputEmail4" placeholder="Adresse mail">
                                </div>
                                <div class="form-group col-md-6">
                                <input type="password" class="form-control" id="inputPassword4" placeholder="Mot de passe">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="gridCheck">
                                <label class="form-check-label" for="gridCheck">
                                    se souvenir de moi
                                </label>
                                </div>
                            </div>
                            <button type="submit" class="btn butn">Connexion</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        </div> -->

        <!-- MODAL ITEM -->
    <div class="modal fade" id="item_modal" tabindex="-1" role="dialog" aria-labelledby="item_modal_label" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="item_modal_label">Paul Bert</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12 col-md-6">
                        <img src="img/monuments/paul-bert.jpg" alt="statue de paul">
                        </div>
                        <div class="col-12 col-md-6 pl-5">
                            <p>La statue de Paul Bert ou Monument à Paul Bert est une statue représentant Paul Bert érigée sur le Pont Paul-Bert à Auxerre dans l'Yonne en France. Elle est inaugurée le 7 juillet 1889 et a vu sa construction financée par une souscription nationale. Son sculpteur est Émile Peynot, son fondeur est Jaboeuf (de la société Jaboeuf et Bezout) et son architecte est Victor-Auguste Blavette.</p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Télécharger</button>
                </div>
              </div>
            </div>
          </div>
    

    <!--Menu de navigation latéral-->

    <div class="main_menu">
        <nav>
            <ul>
                <li><a class="active"  href="{{ path('home') }}">Accueil</a></li>
                <li><a href="{{ path('galerie') }}">Galerie</a></li>
                <li><a href="{{ path('about') }}">Comment ça marche?</a></li>
                <li><a href="{{ path('contact') }}">Contact</a></li>
            </ul>
        </nav>
    </div>




{% block body %}{% endblock %}





 <!--FOOTER-->
 <footer id="main_footer">
        <div class="main_footer_content row">
            <div class="col-12 col-md-4 mb-4 menu text-center">
                <h3>Menu</h3>
                <ul>
                        <li><a class="active" {% if route == 'home' %}active{% endif %}  href="{{ path('home') }}">Accueil</a></li>
                        <li><a {% if route == 'about' %}active{% endif %}href="{{ path('galerie') }}">Galerie</a></li>
                        <li><a {% if route == 'about' %}active{% endif %} href="{{ path('about') }}">Comment ça marche?</a></li>
                        <li><a {% if route == 'contact' %}active{% endif %} href="{{ path('contact') }}">Contact</a></li>
                        <li><a {% if route == 'mentionslegales' %}active{% endif %} href="{{ path('mentionslegales') }}">Mentions légales</a></li>
                </ul>
            </div>
            <div class="col-12 col-md-4 mb-4 contact text-center">
                <h3>Nous contacter</h3>
                <p>Nom de l'assoc</p>
                <p>Adresse</p>
                <p>00000 Auxerre</p>
            </div>
            <div class="col-12 col-md-4 mb-4 reseaux text-center">
                <h3>Suivez-nous !</h3>
                <ul>
                    <li><a href="#"><i class="fab fa-facebook-square"></i></a></li>
                    <li><a href="#"><i class="fab fa-twitter-square"></i></a></li>
                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
<!--COPY-->
        <div class="col-12 copyr">
            <p>&copy; 2018 - L'Yonne en 3D</p>
        </div>
    </footer>

</main>

 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/ionicons@4.2.0/dist/ionicons.js"></script>

	{# <script>
		var main_url = "{{ absolute_url(path('home')) }}";
		var asset_dir = "{{ absolute_url(asset('/')) }}";
	</script> #}
	{# <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
	<script src="{{ asset('js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('js/main.js') }}"></script>
	<script src="{{ asset('js/app.js') }}"></script> #}
	
	
	{# <script src="https://unpkg.com/ionicons@4.2.0/dist/ionicons.js"></script> #}
	{% block javascripts %}

    {# <script>
		var main_url = "{{ absolute_url(path('home')) }}";
		var asset_dir = "{{ absolute_url(asset('/')) }}";
	</script> #}

    <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
	<script src="{{ asset('js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('js/main.js') }}"></script>
	<script src="{{ asset('js/app.js') }}"></script>
     {% endblock %}
</body>

</html>

front+back/templates/contact.html.twig
{% extends 'base.html.twig' %}
{% block h1 %}Inscription{% endblock %} {% block title %}Inscription{% endblock %} 

{% block body %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>L'Yonne en 3D - Accueil</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="css/style.css">
</head>
<body>



<!--
    MAIN
-->
     <!--CONTACT-->
     <section id="contact">
            <div class="contact_content row pt-5">
                <h1>Contact</h1>
                <div class="col-12">
                    <form method="POST">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                            <input type="email" class="form-control" id="inputEmail4" placeholder="Votre adresse mail">
                            </div>
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control" id="firts_name" placeholder="Votre nom">
                            </div>
                            <div class="form-group col-12">
                                <input type="text" class="form-control" id="object" placeholder="Objet">
                            </div>
                            <div class="form-group col-12">
                                <textarea class="form-control" name="adress" rows="6" cols="30" placeholder="Votre message" required></textarea>
                            </div>
                        </div>
                        <div>
                            <input id="btnvalid" class=" mt-2 btn butn" required="produits" type="submit" value="Envoyer" required="required">
                            <input id="btnreset" class=" mt-2 btn butn" type="reset" value="Annuler"/>
                        </div>
                    </form>  
                </div>
    
               
                
            </div>  
        </section>

</body>
</html>

{% endblock %}


{% block javascript %}{% endblock %}

front+back/templates/galerie.html.twig
{% extends 'base.html.twig' %}
 {% block title %}Gallerie{% endblock %}  

{% block body %}



<!--
    MODAL ITEM
-->
<div class="modal fade" id="
galerieitem_modal" tabindex="-1" role="dialog" aria-labelledby="galerieitem_modal_label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="galerieitem_modal_label">Statue de Paul Bert</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <img class="img-fluid" src="img/monuments/paul-bert.jpg" alt="Statue Paul Bert">
                    </div>
                    <div class="col-12 col-md-6">
                        <p>La statue de Paul Bert ou Monument à Paul Bert est une statue représentant Paul Bert érigée sur le Pont Paul-Bert à Auxerre dans l'Yonne en France. Elle est inaugurée le 7 juillet 1889 et a vu sa construction financée par une souscription nationale. Son sculpteur est Émile Peynot, son fondeur est Jaboeuf (de la société Jaboeuf et Bezout) et son architecte est Victor-Auguste Blavette.</p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-6">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Télécharger</button>
                    </div>
                    <div class="col-6">
                        <a href=""><i class="fas fa-heart"></i></a>
                        <a href=""><i class="fas fa-star"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--
    MAIN
-->
    <main>
             <!--GALERIE-->
             {% block h1 %}Gallerie{% endblock %}
        <section id="main_galerie">
                <div class="main_galerie_content row text-center pt-5">
    
                    <div class="col-12 col-md-4">
                        <a data-toggle="modal" data-target="#item_modal">
                            <img class="img-fluid" src="img/monuments/paul-bert.jpg" alt="2">    
                        </a>
                    </div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/abbaye.jpg" alt="2"></div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/eglise-st-etienne.jpg" alt="2"></div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/musee.jpg" alt="2"></div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/st-pierre.jpg" alt="2"></div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/st-eusebe.jpg" alt="2"></div>
                        <!-- <div class="col-12 mt-5">
                            <a class="btn_1" href="">Plus de monuments</a>
                        </div>
         -->
                    </div>
                </section>
                <script src="../js/three.js"></script>
                <script src="../js/STLLoader.js"></script>
                                <script src="../js/Detector.js"></script>
                                <script src="../js/OrbitControls.js"></script>
                                <script src="../js/handLoader.js"></script>







{# </body> #}
{# </html> #}

{% endblock %}


{% block javascript %}{% endblock %}

front+back/templates/index.html.twig
{% extends 'base.html.twig' %} {% block h1 %}Yonne en 3D{% endblock %} {% block title %}Yonne en 3D{% endblock %} {% block body %}

<div aria-label="breadcrumb">
    <ol class="breadcrumb mt-0">
        <li class="breadcrumb-item"><a href="{{ path('home') }}">Accueil</a></li>
    </ol>
</div>

<!--
    MAIN
-->
<main>

        <!-- BANNER -->
            <section id="main_banner">
                <div class="main_banner_content text-center">
                    <img class="banner_img" src="img/wallpaper.jpg" alt="Auxerre">
                    <div class="banner_content_container text-center">
                        <h1>Découvrez l'Yonne en 3D</h1>
    
                        <a class="btn_2" href="{{ path('galerie') }}">Découvrir</a>
                        <a class="btn_3"   href="{{ path('register') }}">S'inscrire</a>
                    </div>
                </div>
            </section>
    
        <!--GALERIE-->
        <section id="main_galerie">
                <div class="main_galerie_content row text-center">
    
                    <div class="col-12 col-md-4">
                        <a data-toggle="modal" data-target="#item_modal">
                            <img class="img-fluid" src="img/monuments/paul-bert.jpg" alt="2">    
                        </a>
                    </div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/abbaye.jpg" alt="2"></div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/eglise-st-etienne.jpg" alt="2"></div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/musee.jpg" alt="2"></div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/st-pierre.jpg" alt="2"></div>
                    <div class="col-12 col-md-4">
                        <img class="img-fluid" src="img/monuments/st-eusebe.jpg" alt="2"></div>
    
                    <div class="col-12 mt-5">
                        <a class="btn_1" href="galerie.html"> En voir plus</a>
                    </div>
    
                </div>
            </section>

 <!--ABOUT-->
 <section id="about">
        <div class="about_content text-center">
            <h2>Comment ça marche?</h2>
            <p class="p_1">Yonne en 3D est un site web, qui permet aux utilisateurs de télécharger dans un premier temps des fichiers en 3D et dans un second temps pouvoir partager des fichiers 3D en lien direct avec la culture artistique et culturelle afin de pouvoir les imprimer en 3D à l’aide de nouvelle technologie telle que la numérisation et l’impression 3D.</p>
            
            <p class="p_2">1.<br> Pour télécharger des fichiers rendez vous dans l’espace galerie.</p>

            <p class="p_2">2.<br> Une oeuvre, un monument vous plaît? Cliquez sur l’image, une fenêtre apparaîtra et appuyer sur le bouton télécharger.</p>

            <p class="p_2">3.<br> Profitez d’une expérience en 3 dimensions avec les différents monuments Icaunais!</p>
        </div>
    </section>

     
                                


{% endblock %}

front+back/templates/profile.html.twig
 {% extends 'base.html.twig' %} {% block h1 %}Profil utilisateur{% endblock %} {% block title %}Profil utilisateur{% endblock %} {% block body %} {# affiche les info de la personne connectee #}

<div aria-label="breadcrumb">
    <ol class="breadcrumb mt-0">
        <li class="breadcrumb-item"><a href="{{ path('home') }}">Accueil</a></li>
        <li class="breadcrumb-item active" aria-current="page"><a href="#">Profil</a></li>
    </ol>
</div>

<!-- slogan -->
<div class="jumbotron">

    <h2>
        <ion-icon name="contact"></ion-icon>Profil </h2>

</div>

{% if success is defined %} {% endif %} {% if success is defined %}
<div class="alert alert-success" role="alert">
    {% for succ in success %} {{ succ }} {% endfor %}
</div>
{% endif %} {% if errors is defined %} {% for error in errors %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endfor %} {% endif %}
<div class="album py-4 p-3 bg-light">

    <div class="row">
        <div class="col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-6 offset-xl-3">
            <div class="card mb-4 mt-5 box-shadow">
                <div class="col-lg-12" id="profil">
                  
                    <label for="nom"><h2>Présentation</h2>
                <p> <ion-icon name="contact"></ion-icon>Nom: {{ app.session.get('account').name}}</p> 
                <p><ion-icon name="mail"></ion-icon> {{ app.session.get('account').email}}</p>
               {# <p> <ion-icon name="copy"></ion-icon>Inscrit le: {{ app.session.get('account').registerDate|date('d-m-Y') }}</p>
                <p> <ion-icon name="call"></ion-icon>Tél:{% if app.session.get('account').phone is not null %} {{ app.session.get('account').phone}} {% else %} Pas de numéro {% endif %}</p> #}
            </label>
                </div>
               {# <div class="btn-group">
                    <form class="col-12 " action="{{ path('api_upload') }}" method="POST" enctype="multipart/form-data">

                        <label for="picture_updload"></label>
                        <input type="file" name="picture_updload" id="picture_updload">


                        <input type="hidden" name="MAX_FILE_SIZE" value="{{ uploaded_file_max_size }}">

                        <button class="btn btn-primary" type="submit"><ion-icon name="arrow-back"></ion-icon> Upload de l'image</button>
                    </form>
                </div>

                <button type="button" class="btn btn-primary m-4" data-toggle="modal" data-target="#exampleModal">
                            Modifier Profil <ion-icon name="create"></ion-icon>
                          </button> 
            </div>#}
            <small class="text-muted"></small>
        </div>
    </div>

</div>



<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Changer votre profil</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-body">

                {# body modal #}
                <form action="{{ path('api_edit_profile', {id:app.session.get('account').id, token:app.session.get('account').activationToken}) }}" method="POST">
                    <div class="form-row">
                        <div class="col-12">
                            <label for="validationDefault01">Nom :</label>
                            <input type="text" name="name" class="form-control" id="validationDefault01" value="{{ app.session.get('account').name}}">
                        </div>
                       
                        <div class="input-group col-12">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="inputGroupPrepend2">@</span>
                            </div>
                            <input type="text" class="form-control" id="validationDefaultUsername" name="email" value="{{ app.session.get('account').email}}" aria-describedby="inputGroupPrepend2" disabled>
                        </div>
                        <div class="input-group-append">

   
                        </div>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                <button type="submit" class="btn btn-primary">Valider</button>
            </div>
        </div>
    </div>
</div>
</form>
{% endblock %} {% block javascript %}{% endblock %}